// Auto-generated by sync-affirmations.js
export interface Affirmation {
    id: string;
    text: string;
    author: string;
    category: string;
}

const moodMapping: Record<string, string[]> = {
    Calma: ['Ansiedad', 'Estrés', 'Paz', 'Relajación', 'Calma', 'Serenidad', 'Entrega'],
    Fuerza: ['Motivación', 'Poder', 'Éxito', 'Protección', 'Libertad', 'Insight'],
    Amor: ['Amor', 'Relaciones', 'Familia', 'Perdón', 'Comunidad', 'Autoestima'],
    Crecimiento: ['Crecimiento', 'Insight', 'Intuición', 'Creatividad'],
    Bienestar: ['Salud', 'Autocuidado', 'Sanación', 'Bienestar'],
    Abundancia: ['Abundancia', 'Gratitud', 'Alegría', 'Dicha', 'Agradecimiento'],
    Confianza: ['Confianza', 'Seguridad', 'Amor Propio', 'Valor', 'Apoyo', 'Liberación'],
    Claridad: ['Enfoque', 'Mentalidad', 'Conciencia', 'Presencia', 'Revelación', 'Mente'],
};

const affirmations: Affirmation[] = [
    {
        "id": "1",
        "text": "Tus pensamientos no son hechos — Reconozco que mi ansiedad me miente; elijo observar sin controlarme.",
        "author": "Aaron Beck",
        "category": "Ansiedad"
    },
    {
        "id": "2",
        "text": "No te afanes por el mañana — Mi mente está en paz con el presente; me enfoco solo en el siguiente paso.",
        "author": "Mateo 6:34",
        "category": "Ansiedad"
    },
    {
        "id": "3",
        "text": "Echando toda ansiedad sobre él — Hoy suelto lo que no controlo y descanso sabiendo que estoy sostenido.",
        "author": "1 Pedro 5:7",
        "category": "Ansiedad"
    },
    {
        "id": "4",
        "text": "Mis emociones son señales, no sentencias. — Me permito sentir mi ansiedad sabiendo que pronto pasará.",
        "author": "Albert Ellis",
        "category": "Ansiedad"
    },
    {
        "id": "5",
        "text": "Mi ansiedad es una alarma falsa. — Agradezco a mi cuerpo por protegerme, pero estoy a salvo ahora.",
        "author": "David Carbonell",
        "category": "Ansiedad"
    },
    {
        "id": "6",
        "text": "La única salida es a través — Tengo el coraje de enfrentar esto; confío en mi capacidad para superarlo.",
        "author": "Robert Frost",
        "category": "Estrés"
    },
    {
        "id": "7",
        "text": "Venid a mí los cargados y os haré descansar. — Hoy suelto mi carga de estrés y me permito un descanso.",
        "author": "Mateo 11:28",
        "category": "Estrés"
    },
    {
        "id": "8",
        "text": "Puedo tolerar la incomodidad. — Esta situación es incómoda, pero no insoportable; yo soy más grande.",
        "author": "Albert Ellis",
        "category": "Estrés"
    },
    {
        "id": "9",
        "text": "Eres más fuerte de lo que crees. — Activo mi fuerza interior; soy capaz de transformar este obstáculo.",
        "author": "Marco Aurelio",
        "category": "Motivación"
    },
    {
        "id": "10",
        "text": "Todo lo puedo en Cristo que me fortalece. — Siento cómo su energía me da la fortaleza para continuar.",
        "author": "Filipenses 4:13",
        "category": "Motivación"
    },
    {
        "id": "11",
        "text": "Los que esperan a Jehová tendrán nuevas fuerzas. — Mi agotamiento desaparece; mi vitalidad se restaura.",
        "author": "Isaías 40:31",
        "category": "Motivación"
    },
    {
        "id": "12",
        "text": "El que al viento observa, no sembrará. — Dejo de esperar el momento perfecto; arranco motores y actúo.",
        "author": "Eclesiastés 11:4",
        "category": "Motivación"
    },
    {
        "id": "13",
        "text": "No busques que los eventos sucedan como quieres. — Renuncio a forzar las cosas; fluyo y me adapto.",
        "author": "Epicteto",
        "category": "Enfoque"
    },
    {
        "id": "14",
        "text": "Puestos los ojos en Jesús. — Corto toda distracción; mantengo mis ojos en mis objetivos con disciplina.",
        "author": "Hebreos 12:2",
        "category": "Enfoque"
    },
    {
        "id": "15",
        "text": "Fluyo como el agua con lo que está fuera de mi control y tengo la sabiduría para adaptarme.",
        "author": "Reinhold Niebuhr",
        "category": "Calma"
    },
    {
        "id": "16",
        "text": "Lo que resistes, persiste. — Observo el mundo fluir sin juzgar. Elijo aceptar mi realidad en paz.",
        "author": "Carl Jung",
        "category": "Calma"
    },
    {
        "id": "17",
        "text": "Cada respiración es una oportunidad de empezar de nuevo. — Me perdono y reinicio mi ciclo de paz aquí.",
        "author": "Thich Nhat Hanh",
        "category": "Calma"
    },
    {
        "id": "18",
        "text": "Estoy dispuesto a cambiar y crecer. — Mi expansión está perfectamente cuidada dentro de mi consciencia.",
        "author": "Louise Hay",
        "category": "Crecimiento"
    },
    {
        "id": "19",
        "text": "Todo está bien al equivocarme. — Los errores son simples datos invaluables para perfeccionar mi progreso.",
        "author": "Louise Hay",
        "category": "Crecimiento"
    },
    {
        "id": "20",
        "text": "He aquí, yo hago nuevas todas las cosas. — Cada amanecer es un inicio ilimitado para hacer las cosas mejor.",
        "author": "Apocalipsis 21:5",
        "category": "Crecimiento"
    },
    {
        "id": "21",
        "text": "El fracaso es un evento, no una identidad. — Lo reciclo ágilmente en retroalimentación para crecer.",
        "author": "Carol Dweck",
        "category": "Crecimiento"
    },
    {
        "id": "22",
        "text": "Me siento seguro y a salvo. — Libero la zozobra y declaro la paz total, estoy fuera de peligro hoy.",
        "author": "Louise Hay",
        "category": "Seguridad"
    },
    {
        "id": "23",
        "text": "Me amo y me apruebo tal como soy. — Aprecio con devoción las características exclusivas de mi propio ser.",
        "author": "Louise Hay",
        "category": "Amor Propio"
    },
    {
        "id": "24",
        "text": "No temas, porque yo estoy contigo. — Una muralla espiritual rodea mi ser y silencia el ruido exterior.",
        "author": "Isaías 41:10",
        "category": "Seguridad"
    },
    {
        "id": "25",
        "text": "Ama a tu prójimo como a ti mismo. — Me doy a mí la misma prioridad y comprensión que entrego a otros.",
        "author": "Marcos 12:31",
        "category": "Amor Propio"
    },
    {
        "id": "26",
        "text": "Soy suficiente tal como soy ahora. — Asumo y manifiesto la suficiencia vital que resplandece en mi ser.",
        "author": "Brené Brown",
        "category": "Amor Propio"
    },
    {
        "id": "27",
        "text": "Todo lo que necesito saber se me revela. — Mantengo atentas mis antenas, sabiendo que soy guiado.",
        "author": "Louise Hay",
        "category": "Revelación"
    },
    {
        "id": "28",
        "text": "El pasado ha terminado. — Me anclo con firmeza en el único momento que realmente existe: este presente.",
        "author": "Louise Hay",
        "category": "Presencia"
    },
    {
        "id": "29",
        "text": "El momento presente es el único que existe. — Disuelvo proyecciones torturosas y me fundo en pura paz.",
        "author": "Eckhart Tolle",
        "category": "Presencia"
    },
    {
        "id": "30",
        "text": "Estoy dispuesto a curarme. — Permito que mi mente sane, soltando el dolor y abrazando la recuperación.",
        "author": "Louise Hay",
        "category": "Sanación"
    },
    {
        "id": "31",
        "text": "Estoy dispuesto a perdonar. — Libero los rencores del pasado para regalarme paz interior y libertad.",
        "author": "Louise Hay",
        "category": "Perdón"
    },
    {
        "id": "32",
        "text": "Tengo el poder de ser instrumento de sanación. — Declaro una catarata celestial renovando mis células.",
        "author": "Mateo 10:8",
        "category": "Sanación"
    },
    {
        "id": "33",
        "text": "Perdona setenta veces siete. — Comprendo que perdonar constantemente me protege y me permite vivir en paz.",
        "author": "Mateo 18:22",
        "category": "Perdón"
    },
    {
        "id": "34",
        "text": "Doy bienvenida a la abundancia. — Acepto con gratitud las oportunidades que la vida me ofrece cada día.",
        "author": "Louise Hay",
        "category": "Abundancia"
    },
    {
        "id": "35",
        "text": "El Señor es mi pastor. — Dejo atrás el miedo a la escasez y confío en que mis necesidades serán provistas.",
        "author": "Salmos 23:1",
        "category": "Abundancia"
    },
    {
        "id": "36",
        "text": "Dad gracias en todo. — Valoro cada instante y encuentro motivos para agradecer, multiplicando lo bueno.",
        "author": "1 Tesalonicenses 5:18",
        "category": "Gratitud"
    },
    {
        "id": "37",
        "text": "La paz os dejo. — Recibo esta serenidad, permitiendo que calme mi mente y silencie el ruido del mundo.",
        "author": "Juan 14:27",
        "category": "Paz"
    },
    {
        "id": "38",
        "text": "El gozo del Señor es mi fortaleza. — Mi alegría espiritual me protege del desánimo y me llena de energía.",
        "author": "Nehemías 8:10",
        "category": "Alegría"
    },
    {
        "id": "39",
        "text": "«Yo soy la luna en el agua». — Los eventos externos son pasajeros; mantengo mi centro en calma total.",
        "author": "Proverbio Zen",
        "category": "Presencia"
    },
    {
        "id": "40",
        "text": "Asumo el control de mi mente estableciendo nuevos hábitos positivos y liberándome de miedos del pasado.",
        "author": "Joe Dispenza",
        "category": "Crecimiento"
    },
    {
        "id": "41",
        "text": "El miedo es mi radar. — No huyo de él, lo utilizo como brújula para enfrentar mis retos con valentía.",
        "author": "Ryan Holiday",
        "category": "Confianza"
    },
    {
        "id": "42",
        "text": "Suelto la nostalgia y la preocupación, decidiendo habitar plenamente y en paz este presente seguro.",
        "author": "Lao Tse",
        "category": "Paz"
    },
    {
        "id": "43",
        "text": "No eres la gota en el océano, eres el océano entero. — Reconozco mi valor y grandeza infinitos hoy.",
        "author": "Rumi",
        "category": "Amor Propio"
    },
    {
        "id": "44",
        "text": "Mi respiración es el puente que me conecta con la vida y la conciencia en este momento.",
        "author": "Thich Nhat Hanh",
        "category": "Paz Mental"
    },
    {
        "id": "45",
        "text": "Para que las cosas se revelen, elijo estar listo para abandonar mis puntos de vista tradicionales.",
        "author": "Thich Nhat Hanh",
        "category": "Crecimiento"
    },
    {
        "id": "46",
        "text": "Sonrío a la nube gris dentro de mí; reconozco mi dolor sin que me defina.",
        "author": "Thich Nhat Hanh",
        "category": "Ansiedad"
    },
    {
        "id": "47",
        "text": "Bebo mi té despacio y con reverencia, como si este acto fuera el eje sobre el que gira el mundo.",
        "author": "Thich Nhat Hanh",
        "category": "Paz Mental"
    },
    {
        "id": "48",
        "text": "No puedo detener las olas de la vida, pero elijo aprender a surfearlas.",
        "author": "Jon Kabat-Zinn",
        "category": "Crecimiento"
    },
    {
        "id": "49",
        "text": "Me permito estar plenamente donde estoy, abrazando este instante por completo.",
        "author": "Jon Kabat-Zinn",
        "category": "Ansiedad"
    },
    {
        "id": "50",
        "text": "Reconozco profundamente que el momento presente es lo único que tengo.",
        "author": "Eckhart Tolle",
        "category": "Paz Mental"
    },
    {
        "id": "51",
        "text": "Cualquier cosa que este momento contenga, la acepto plenamente como si yo mismo la hubiera elegido.",
        "author": "Eckhart Tolle",
        "category": "Paz Mental"
    },
    {
        "id": "52",
        "text": "No me preocupo por el futuro; encuentro mi fuerza en lidiar con el ahora.",
        "author": "Eckhart Tolle",
        "category": "Ansiedad"
    },
    {
        "id": "53",
        "text": "Dejo ir mi resistencia interna; la paz fluye cuando dejo de pelear con lo que es.",
        "author": "Eckhart Tolle",
        "category": "Dormir"
    },
    {
        "id": "54",
        "text": "Mis pensamientos no son hechos absolutos, son solo eventos mentales pasajeros que no me controlan.",
        "author": "Aaron Beck",
        "category": "Ansiedad"
    },
    {
        "id": "55",
        "text": "No soy perturbado por lo que sucede, sino por mi visión de lo que sucede. Elijo la perspectiva de la calma.",
        "author": "Albert Ellis",
        "category": "Paz Mental"
    },
    {
        "id": "56",
        "text": "Dejo de exigir que el mundo sea fácil, y en su lugar construyo tolerancia a la incomodidad.",
        "author": "Albert Ellis",
        "category": "Crecimiento"
    },
    {
        "id": "57",
        "text": "No catastrofizo mi futuro; elijo centrarme en las soluciones de mi presente.",
        "author": "Aaron Beck",
        "category": "Ansiedad"
    },
    {
        "id": "58",
        "text": "Acepto que equivocarme no me hace un fracaso, solo me hace un ser humano aprendiendo.",
        "author": "Albert Ellis",
        "category": "Autoestima"
    },
    {
        "id": "59",
        "text": "Entre lo que pasa y mi reacción, existe un espacio consciente. En ese espacio reside mi poder para calmarme.",
        "author": "Viktor Frankl",
        "category": "Focus"
    },
    {
        "id": "60",
        "text": "Incluso cuando no puedo cambiar una situación, siempre mantengo y defiendo mi libertad de elegir mi actitud.",
        "author": "Viktor Frankl",
        "category": "Paz Mental"
    },
    {
        "id": "61",
        "text": "Encuentro significado incluso en mi sufrimiento, sabiendo que me forja en alguien más fuerte.",
        "author": "Viktor Frankl",
        "category": "Crecimiento"
    },
    {
        "id": "62",
        "text": "No soy lo que me ha sucedido; soy la persona en la que elijo convertirme a partir de hoy.",
        "author": "Carl Jung",
        "category": "Autoestima"
    },
    {
        "id": "63",
        "text": "Miro mi propia oscuridad para poder tener visión; entiendo que la luz nace de la sombra.",
        "author": "Carl Jung",
        "category": "Crecimiento"
    },
    {
        "id": "64",
        "text": "Hasta que no haga consciente lo inconsciente, dejaré de llamarle destino a lo que me sucede.",
        "author": "Carl Jung",
        "category": "Focus"
    },
    {
        "id": "65",
        "text": "La curiosa paradoja es que cuando logro finalmente aceptarme a mí mismo, es justo cuando empiezo a cambiar.",
        "author": "Carl Rogers",
        "category": "Autoestima"
    },
    {
        "id": "66",
        "text": "Me permito ser un proceso fluido, dejando ir la necesidad de ser una entidad estática y terminada.",
        "author": "Carl Rogers",
        "category": "Crecimiento"
    },
    {
        "id": "67",
        "text": "Confío en mi propia experiencia orgánica por encima del juicio externo.",
        "author": "Carl Rogers",
        "category": "Autoestima"
    },
    {
        "id": "68",
        "text": "Tengo poder sobre mi mente, no sobre los eventos de afuera. Al darme cuenta, mi fuerza se hace irrompible.",
        "author": "Marco Aurelio",
        "category": "Ansiedad"
    },
    {
        "id": "69",
        "text": "Reconozco que sufro más en mi propia imaginación que en la realidad tangible.",
        "author": "Séneca",
        "category": "Ansiedad"
    },
    {
        "id": "70",
        "text": "No es lo que me sucede, sino cómo elijo reaccionar a ello lo que define mi vida.",
        "author": "Epicteto",
        "category": "Crecimiento"
    },
    {
        "id": "71",
        "text": "Obstáculo es el camino; uso esta adversidad actual como combustible para mi avance.",
        "author": "Marco Aurelio",
        "category": "Focus"
    },
    {
        "id": "72",
        "text": "Mi mente se tiñe del color de mis pensamientos; hoy elijo pensamientos de serenidad y virtud.",
        "author": "Marco Aurelio",
        "category": "Paz Mental"
    },
    {
        "id": "73",
        "text": "La suerte es lo que sucede cuando la preparación extrema se encuentra con la oportunidad.",
        "author": "Séneca",
        "category": "Focus"
    },
    {
        "id": "74",
        "text": "Me permito ser vulnerable. Reconozco que es mi mayor medida de coraje, no de debilidad.",
        "author": "Brené Brown",
        "category": "Autoestima"
    },
    {
        "id": "75",
        "text": "Dejo ir la meta de ser perfecto y abrazo mi propia autenticidad con compasión.",
        "author": "Brené Brown",
        "category": "Autoestima"
    },
    {
        "id": "76",
        "text": "Hablar de mis miedos les quita el poder que tienen sobre mí.",
        "author": "Brené Brown",
        "category": "Ansiedad"
    },
    {
        "id": "77",
        "text": "Me trato hoy mismo con la misma amabilidad, cuidado infinito y paciencia que le daría a un buen amigo.",
        "author": "Kristin Neff",
        "category": "Autoestima"
    },
    {
        "id": "78",
        "text": "Reconozco que el dolor es parte de la experiencia humana compartida; no estoy solo en lo que siento.",
        "author": "Kristin Neff",
        "category": "Ansiedad"
    },
    {
        "id": "79",
        "text": "En lugar de juzgarme sin piedad, elijo abrazarme con suavidad en este momento difícil.",
        "author": "Kristin Neff",
        "category": "Paz Mental"
    },
    {
        "id": "80",
        "text": "Digo firmemente \"sí\" a lo que está sucediendo en mi interior en este momento, rindiéndome con amabilidad.",
        "author": "Tara Brach",
        "category": "Paz Mental"
    },
    {
        "id": "81",
        "text": "Hago una pausa. Respiro. Reconozco qué está pasando y lo permito simplemente estar ahí.",
        "author": "Tara Brach",
        "category": "Ansiedad"
    },
    {
        "id": "82",
        "text": "El caos frente a mí es el lugar perfecto para despertar y crecer; no huyo de él.",
        "author": "Pema Chödrön",
        "category": "Crecimiento"
    },
    {
        "id": "83",
        "text": "Dejo que esta incomodidad me suavice el corazón en lugar de endurecerme.",
        "author": "Pema Chödrön",
        "category": "Paz Mental"
    },
    {
        "id": "84",
        "text": "Entiendo que la herida es precisamente el lugar por donde la luz entra en mí.",
        "author": "Rumi",
        "category": "Crecimiento"
    },
    {
        "id": "85",
        "text": "Acepto quien soy y, al hacerlo, me doy cuenta de que todo el universo estaba ya dentro de mí.",
        "author": "Rumi",
        "category": "Autoestima"
    },
    {
        "id": "86",
        "text": "La naturaleza nunca jamás se apresura, y sin embargo todo lo logra. Respiro conectándome con ese ritmo.",
        "author": "Lao Tsé",
        "category": "Ansiedad"
    },
    {
        "id": "87",
        "text": "Al dejar ir de lo que soy, elijo convertirme en aquello en lo que podría llegar a ser.",
        "author": "Lao Tsé",
        "category": "Crecimiento"
    },
    {
        "id": "88",
        "text": "El sueño es un puente seguro entre este día y mi mañana. Cruzo con total confianza.",
        "author": "Matthew Walker",
        "category": "Dormir"
    },
    {
        "id": "89",
        "text": "Mi mente consciente ha hecho suficiente por hoy; autorizo a mi subconsciente a descansar en calma.",
        "author": "Joseph Murphy",
        "category": "Dormir"
    },
    {
        "id": "90",
        "text": "Libero completamente todas las exigentes expectativas del mañana y me sumerjo en la sanación del sueño.",
        "author": "Dr. Andrew Huberman",
        "category": "Dormir"
    },
    {
        "id": "91",
        "text": "El descanso profundo no es un lujo, es el cimiento absoluto de mi sistema nervioso.",
        "author": "Dr. Andrew Huberman",
        "category": "Dormir"
    },
    {
        "id": "92",
        "text": "Me perdono por lo que no logré hoy. La noche está aquí y yo decido soltar las cargas.",
        "author": "Kristin Neff",
        "category": "Dormir"
    },
    {
        "id": "93",
        "text": "Miro la oscuridad con comodidad. En este silencio mi cuerpo se regenera totalmente.",
        "author": "Jon Kabat-Zinn",
        "category": "Dormir"
    },
    {
        "id": "94",
        "text": "Mantengo mi atención fijada en el siguiente paso obvio. No necesito ver la escalera completa para subir.",
        "author": "Martin Luther King Jr.",
        "category": "Focus"
    },
    {
        "id": "95",
        "text": "No pierdo mi energía vital en cosas fuera de mi control; concentro todo mi poder solo en lo que sí puedo.",
        "author": "Stephen Covey",
        "category": "Focus"
    },
    {
        "id": "96",
        "text": "Mis hábitos de hoy, por pequeños e imperceptibles que sean, esculpen mi identidad. Elijo seguir esforzándome.",
        "author": "James Clear",
        "category": "Focus"
    },
    {
        "id": "97",
        "text": "Las distracciones retroceden; mi capacidad cognitiva y mi voluntad permanecen afiladas y presentes.",
        "author": "Cal Newport",
        "category": "Focus"
    },
    {
        "id": "98",
        "text": "Donde coloco mi atención fluye mi energía. Hoy elijo enfocarme estrictamente en mi progreso.",
        "author": "Tony Robbins",
        "category": "Focus"
    },
    {
        "id": "99",
        "text": "Acepto el hermoso estado de flujo mental. Mi energía viva se alza para encontrar el ritmo de este instante.",
        "author": "Mihaly Csikszentmihalyi",
        "category": "Focus"
    },
    {
        "id": "100",
        "text": "Me apruebo a mí mismo profundamente y sin condiciones en este mismo momento.",
        "author": "Louise Hay",
        "category": "Autoestima"
    },
    {
        "id": "101",
        "text": "Soy digno de amor, no porque me lo haya ganado, sino simplemente porque existo.",
        "author": "Louise Hay",
        "category": "Autoestima"
    },
    {
        "id": "102",
        "text": "Renuncio al patrón en mi mente que crea resistencia. Elijo amarme exactamente como soy hoy.",
        "author": "Louise Hay",
        "category": "Autoestima"
    },
    {
        "id": "103",
        "text": "Miro mi cuerpo con ojos de amor y aprecio cada cosa maravillosa que hace por mí.",
        "author": "Louise Hay",
        "category": "Autoestima"
    },
    {
        "id": "104",
        "text": "Mi corazón y mi mente están abiertos profundamente para recibir y dar amor.",
        "author": "Louise Hay",
        "category": "Amor Propio"
    },
    {
        "id": "105",
        "text": "Estoy dispuesto a soltar mis miedos. Solo son pensamientos y los pensamientos pueden cambiar.",
        "author": "Louise Hay",
        "category": "Ansiedad"
    },
    {
        "id": "106",
        "text": "Todo está bien en mi mundo. Estoy a salvo y el Universo siempre provee para mis necesidades.",
        "author": "Louise Hay",
        "category": "Ansiedad"
    },
    {
        "id": "107",
        "text": "Libero el pasado con amor y elijo fluir suavemente hacia este nuevo momento.",
        "author": "Louise Hay",
        "category": "Paz Mental"
    },
    {
        "id": "108",
        "text": "Solo atraigo experiencias maravillosas porque estoy alineado con la calma de la vida.",
        "author": "Louise Hay",
        "category": "Ansiedad"
    },
    {
        "id": "109",
        "text": "Tengo dentro de mí todo lo que necesito para superar este obstáculo.",
        "author": "Louise Hay",
        "category": "Crecimiento"
    },
    {
        "id": "110",
        "text": "Estoy en el proceso de un cambio positivo constante. Me permito evolucionar con gracia.",
        "author": "Louise Hay",
        "category": "Crecimiento"
    },
    {
        "id": "111",
        "text": "Cada nuevo día me ofrece una oportunidad perfecta para comenzar de nuevo.",
        "author": "Louise Hay",
        "category": "Crecimiento"
    },
    {
        "id": "112",
        "text": "Perdono fácilmente. Elijo soltar el resentimiento porque mi libertad emocional es lo más importante.",
        "author": "Louise Hay",
        "category": "Paz Mental"
    },
    {
        "id": "113",
        "text": "Dondequiera que voy encuentro amor y paz, porque eso es exactamente lo que llevo en mi corazón.",
        "author": "Louise Hay",
        "category": "Paz Mental"
    },
    {
        "id": "114",
        "text": "Dejo que la paz interior dirija mi vida. Mi respiración fluye profundamente y todo mi ser se relaja.",
        "author": "Louise Hay",
        "category": "Paz Mental"
    },
    {
        "id": "115",
        "text": "Me doy a mí mismo el regalo del silencio, comprendiendo que allí residen todas las respuestas.",
        "author": "Louise Hay",
        "category": "Paz Mental"
    },
    {
        "id": "116",
        "text": "Merezco lo mejor y acepto lo mejor ahora mismo. Abro mis brazos a la abundancia del universo.",
        "author": "Louise Hay",
        "category": "Focus"
    },
    {
        "id": "117",
        "text": "Mi vida es una alegría y fluye con propósito, dirección y significado.",
        "author": "Louise Hay",
        "category": "Focus"
    },
    {
        "id": "118",
        "text": "Dejo ir toda competencia y comparación; hay suficiente espacio y recursos para todos nosotros.",
        "author": "Louise Hay",
        "category": "Focus"
    },
    {
        "id": "119",
        "text": "Cierro mis pesados ojos confirmando que mi trabajo hoy está completo y que he ganado el merecido descanso.",
        "author": "Louise Hay",
        "category": "Dormir"
    },
    {
        "id": "120",
        "text": "En este momento suave y nocturno me perdono completamente los errores de hoy y me hundo en profundo sueño.",
        "author": "Louise Hay",
        "category": "Dormir"
    },
    {
        "id": "121",
        "text": "Dejo que mis múltiples inquietudes se desintegren en el aire oscuro. Mi mente en calma se dedica a sanar.",
        "author": "Louise Hay",
        "category": "Dormir"
    },
    {
        "id": "122",
        "text": "No me afano por el misterioso mañana; decido intencionalmente enfocarme solo en el paso que veo hoy.",
        "author": "Mateo 6:34",
        "category": "Paz Mental"
    },
    {
        "id": "123",
        "text": "Echo toda mi ansiedad sobre Él, porque sé que Él tiene cuidado de mí.",
        "author": "1 Pedro 5:7",
        "category": "Ansiedad"
    },
    {
        "id": "124",
        "text": "La paz suprema de Dios que evidentemente sobrepasa todo este entendimiento, guarda celosamente mi corazón.",
        "author": "Filipenses 4:7",
        "category": "Paz Mental"
    },
    {
        "id": "125",
        "text": "No me ha dado Dios un espíritu de cobardía, sino de poder, de amor y de dominio propio.",
        "author": "2 Timoteo 1:7",
        "category": "Focus"
    },
    {
        "id": "126",
        "text": "En paz me acuesto y asimísmo duermo, porque solo Tú me haces vivir confiado.",
        "author": "Salmos 4:8",
        "category": "Dormir"
    },
    {
        "id": "127",
        "text": "Todo lo puedo y logro en Aquel que me fortalece. Mi fuerza vital proviene enteramente de una fuente divina.",
        "author": "Filipenses 4:13",
        "category": "Crecimiento"
    },
    {
        "id": "128",
        "text": "Aunque ande en valle de sombra, no temeré mal alguno, porque Tú estás conmigo.",
        "author": "Salmos 23:4",
        "category": "Ansiedad"
    },
    {
        "id": "129",
        "text": "Mi fe es la certeza de lo que espero, la convicción de lo que aún no veo.",
        "author": "Hebreos 11:1",
        "category": "Focus"
    },
    {
        "id": "130",
        "text": "Renuevo mi mente cada día; dejo atrás lo viejo y abrazo la transformación de mi ser.",
        "author": "Romanos 12:2",
        "category": "Crecimiento"
    },
    {
        "id": "131",
        "text": "Busco primero la paz y la justicia, sabiendo que todo lo demás me será añadido a su debido tiempo.",
        "author": "Mateo 6:33",
        "category": "Focus"
    },
    {
        "id": "132",
        "text": "Soy una creación maravillosa; reconozco el valor infinito que se me fue dado desde mi origen.",
        "author": "Salmos 139:14",
        "category": "Autoestima"
    },
    {
        "id": "133",
        "text": "Nada de lo que enfrento hoy podrá separarme del amor incondicional que me sostiene.",
        "author": "Romanos 8:38-39",
        "category": "Autoestima"
    },
    {
        "id": "134",
        "text": "Dejo que el amor perfecto eche fuera todo mi temor; elijo caminar con confianza.",
        "author": "1 Juan 4:18",
        "category": "Ansiedad"
    },
    {
        "id": "135",
        "text": "Soy hechura suya, creado para buenas obras; mi vida tiene un propósito profundo.",
        "author": "Efesios 2:10",
        "category": "Autoestima"
    },
    {
        "id": "136",
        "text": "Vengo a descansar; entrego mis cargas pesadas y recibo a cambio ligereza y paz.",
        "author": "Mateo 11:28",
        "category": "Ansiedad"
    },
    {
        "id": "137",
        "text": "Mi corazón no se turbará ni tendrá miedo. Recibo la paz que se me ha dado.",
        "author": "Juan 14:27",
        "category": "Paz Mental"
    },
    {
        "id": "138",
        "text": "Espero con paciencia; renuevo mis fuerzas y me levanto como las águilas por encima de mis problemas.",
        "author": "Isaías 40:31",
        "category": "Crecimiento"
    },
    {
        "id": "139",
        "text": "Sé profundamente que todos los planes divinos dirigidos a mí son de intenso bienestar y gran esperanza.",
        "author": "Jeremías 29:11",
        "category": "Focus"
    },
    {
        "id": "140",
        "text": "Si me falta sabiduría, la pido con fe, confiando en que se me dará abundantemente.",
        "author": "Santiago 1:5",
        "category": "Focus"
    },
    {
        "id": "141",
        "text": "Guardo mi corazón por sobre todas las cosas, porque sé que de él mana la vida.",
        "author": "Proverbios 4:23",
        "category": "Autoestima"
    },
    {
        "id": "142",
        "text": "No me apoyaré solo en mi propia prudencia; reconozco la guía superior en todos mis caminos.",
        "author": "Proverbios 3:5-6",
        "category": "Paz Mental"
    }
];

export function getAffirmationsByMood(mood: string): Affirmation[] {
    if (mood === 'Todas') return affirmations;
    const subCategories = moodMapping[mood] || [];
    if (subCategories.length === 0) {
        return affirmations.filter(a => a.category.toLowerCase() === mood.toLowerCase());
    }
    return affirmations.filter(a =>
        subCategories.some(sub => sub.toLowerCase() === a.category.toLowerCase())
    );
}

export function getRandomAffirmation(mood: string): Affirmation {
    const list = getAffirmationsByMood(mood);
    if (list.length === 0) return affirmations[0];
    return list[Math.floor(Math.random() * list.length)];
}
